### ISSUE TITLE
Your Monetization setup available 

### ISSUE THREAD

**Issue by Apply-fb** [skills/hello-github-actions#112]
### Summary

A clear and concise description of what the bug is, and what you expected to happen.

### How to reproduce

2. Click on '...'
3. Scroll down to '...'

Please include screenshots.

**Comment by Marlidasilvsa** [comment]
marlidasilvsa1533@gmail.com

**Comment by Marlidasilvsa** [comment]
marlidasilvsa1533@gmail.com
