### ISSUE TITLE
Investigate deeper YAML checking

### ISSUE THREAD

**Issue by heiskr** [skills/hello-github-actions#2]
According to https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md there's a number of YAML tools installed on the Actions runners by default. We could investigate if these tools could offer more checks for learners.

**Comment by michelenoronha** [comment]
adorando aprender

**Comment by hectorsector** [comment]
Thanks for the suggestion! Cleaning up the Skills issue list so I'm closing this out for now.
