### ISSUE TITLE
[Bug] Button 'Use this template' not showing up

### ISSUE THREAD

**Issue by rufer7** [skills/hello-github-actions#32]
**Describe the bug**
I just wanted to so this course but unfortunately can't see the 'Use this template' button.

**To Reproduce**
1. Log in to GitHub
2. Navigate to this repository

**Expected behavior**
See the above mentioned button.

**Screenshots**
![Screenshot_20230206-142639](https://user-images.githubusercontent.com/5937292/216984342-ca10e9f2-1762-4889-b845-b8ada0137b1f.png)

**Device information**
 - Type: Nothing phone
 - OS: android
 - Browser: chrome
 - Version: 109.0.5414.118

**Comment by cmwilson21** [comment]
@rufer7 - Thanks for opening an issue. Is this the only course you are experiencing this problem with? The button is there for me. Can you confirm what computer you are using?

**Comment by rufer7** [comment]
@cmwilson21 It's only happening on my mobile Phone aus pointed out in the description and it happens on all template repos

**Comment by sinsukehlab** [comment]
I found these buttons, **<> Code** and **Use this template**, also disappeared in the Chrome browser on my desktop PC when the window width is narrower than the predetermined width. This issue is about A11Y, for some learners use mobile phones to take this course.

**Comment by heiskr** [comment]
We've updated the courses to include the button you'll need directly in the template, and it will prompt you to log in if you are not. I'll leave the issue open for reference to the repos accessibility team.

**Comment by rufer7** [comment]
Perfect, thanks a lot!

**Comment by heiskr** [comment]
There's an issue the accessibility backlog for this, so I'm going to close this out as there's not much we can do directly from the Skills side.
