### ISSUE TITLE
[Bug] Lab errors with false positive emoji error

### ISSUE THREAD

**Issue by davebunte** [skills/hello-github-actions#7]
**Describe the bug**
The existing `-` character in the word `private-repositories` causes a false positive in the emoji checking script.

**To Reproduce**
1. Run the lab - this generates an unexpected error after step 4 indicating that the line containing "private-repositories" contains an emoji not using an emoji shortcode

**Expected behavior**
Expected the lab to pass after completing the full workflow file

**Screenshots**
<img width="1456" alt="Screen Shot 2022-06-09 at 11 27 39 AM" src="https://user-images.githubusercontent.com/383953/172908326-8dc6ca4c-54e4-419d-99a3-1166e0369886.png">

**Device information**
 - Type: 16" MBP (M1)
 - OS: Monterey 12.4
 - Browser Chrome
 - Version 102.0.5005.61 (Official Build) (arm64)

**Additional context**

**Comment by davebunte** [comment]
The PR I merged should address the issue and allow users to run the lab successfully. However, my "fix" only involved replacing the character causing the false positive detection, eliminating the error from the previous README.md. The better solution might be to adjust the emoji checking script (perhaps something similar to the solution described in [this Slack Overflow post](https://stackoverflow.com/questions/52266347/grep-for-emojis-in-linux)).

**Comment by heiskr** [comment]
Thank you for the pull request :) We've updated this course to instead have the learner make a workflow that posts a comment on new pull requests instead, hopefully that's a little less involved than the emoji check 🤞🏼  I'll go ahead and close out this issue.
